# Generated by Django 6.1 on 2026-08-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_tasklist_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Tablero', 'verbose_name_plural': 'Tableros'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'tarea', 'verbose_name_plural': 'tareas'},
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={'verbose_name': 'lista tarea', 'verbose_name_plural': 'lista de tareas'},
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='title',
            field=models.CharField(default=['Pendientes', 'En progreso', 'Completadas'], max_length=120),
        ),
    ]
