# Generated by Django 6.1 on 2026-08-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
