# Generated by Django 6.1 on 2026-08-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite'),
        ),
    ]
