# Generated by Django 6.1 on 2026-08-13 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('color', models.CharField(choices=[('gray', 'Gris'), ('brand', 'Ámbar'), ('accent', 'Oliva'), ('danger', 'Rojo')], default='Gris', max_length=10, verbose_name='color')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='boards.board')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='boards.label'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='uniq_label_board_name'),
        ),
    ]
