# Generated by Django 6.1 on 2026-08-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_label_task_labels_label_uniq_label_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(choices=[('gray', 'Gris'), ('brand', 'Ámbar'), ('accent', 'Oliva'), ('danger', 'Rojo')], default='gray', max_length=10, verbose_name='color'),
        ),
    ]
